plugins {
    id 'com.github.ben-manes.versions' version '0.21.0'
}

apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'no.novari'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    maven {
        url 'https://repo.fintlabs.no/releases'
    }
    mavenCentral()
}

dependencies {
    implementation 'javax.validation:validation-api:2.0.1.Final'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
}

javadoc {
    source = sourceSets.main.allJava
    classpath = configurations.runtimeClasspath
    options.windowTitle = 'FINT Model Core'
    destinationDir = file('./javadocs/')
}

publishing {
    repositories {
        maven {
            url "https://repo.fintlabs.no/releases"
            credentials {
                username = System.getenv("REPOSILITE_USERNAME")
                password = System.getenv("REPOSILITE_PASSWORD")
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}